### ISSUE TITLE
unable to find image 'mhy:latest' locally

### ISSUE THREAD

**Issue by peterennis** [wintercounter/mhy#16]
Windows 10
Docker Desktop 2.1.0.1

Following instructions here:
https://mhy.js.org/basics/usage

![Capture669](https://user-images.githubusercontent.com/140737/63566287-53adc300-c521-11e9-8e28-9d1bef46b567.png)

Looks like some other permission is needed.

**Comment by wintercounter** [comment]
This is related to docker. You need to run docker login first (yes, even for public images -.-). Don't forget to use your username when logging in and not your e-mail.

See https://github.com/docker/hub-feedback/issues/1103

Also please note that you need the following syntax on Windows for pwd: `%CD%` instead of `$(pwd)`.
I'll add this to the docs today.

In overall tbh I hate to work with Docker on Windows, it has so many issues and performance is crap. For example there are no FileSystem events propagated to the container (eg, Webpack, Jest and such watchers cannot work!), you need a separate app that will forward the events it for you... I'm waiting for WSL2 soooo much, it'll solve all these.

**Comment by wintercounter** [comment]
I deleted my previous comment as I realised there was another issue.

`docker run -it -v %CD%:/app -w /app wintercounter/mhy mhy jest`

The package name is `mhy` on when I built locally for myself. But actually is `wintercounter/mhy`.

Updating the docs. Thanks for the feedback.
